### PR TITLE
feat(android-filechooser): Implement save file method

### LINKED ISSUE #661: Problem: filechooser doesn't work on android
Calling save_file() just returns None without file choose menu!

Tested on: BlueStacks 4

- kivy 2.0.0
- plyer 2.0.0
- python 3.8

**UPD 2022-11**: #728 solves the issue!

### PR DESCRIPTION
**Pull request by leestarb**
**This works like a charm!**
Tested on: _python 3.8.15; kivy 2.1.0;  plyer 2.1.0; Android 13 on pure AOSP_

**Pros:**
- [x] _**This doesn't need any permissions. Neither any manifest nor config changes (Absolutely no any).**_

- [x] _**Always uses the default file explorer in the system.**_

- [x] Purely native code approved by the Google's android guide.

- [x] The same code (but in Kotlin) tested with my production app on **5, 7, 9, 10, 12, 13** versions of Android.

- [x] This supports the default file name value as `title` argument.

- [x] Comfortable handling of the file output stream with the callback argument. Not so good due to the lack of type hints but there always are the java docs!

**Cons:**
Still uses deprecated onActivityResult (same as `open_file` does. I think this is not so bad (This also used on the Google's guide).

Improvements and tests are appreciated!

Closes #661  ;)

### CODE REVIEW

**Comment by leestarb** [comment]
> Hi @leestarb !
> 
> Our style checks are failing on your PR, can you take care of it?

Ok! This is just style issues

**Comment by leestarb** [comment]
I"m sorry for being so late, but I did it. Now please approve the workflows, @misl6 🫠

**Review by misl6 — CHANGES_REQUESTED** [review]
Hi @leestarb 

Please do not apply code styling to all the file (black), but just to the part you changed.

**Comment by leestarb** [comment]
Hello @misl6 . Finally it is OK with the style of code!

**Review by misl6 — APPROVED** [review]
LGTM. Thank you!

Maybe you want to also add that functionality in our examples?

**Pull request merged**
