### PR TITLE
Added logic to support the `on_status` method of the gps facade for i…

### PR DESCRIPTION
**Pull request by Dirk-Sandberg**
Added logic to support the `on_status` method of the gps facade for iOS devices to allow iOS developers to be notified of when a user changes location authorization.

### CODE REVIEW

**Comment by tshirtman** [comment]
@Zen-CODE if you can test, maybe?

**Comment by Zen-CODE** [comment]
@tshirtman Sure, will do, but probably only after Christmas....:-)

**Comment by Zen-CODE** [comment]
When testing, I get the following error.
```
[INFO   ] [Kivy        ] v2.0.0.dev0, git-921f6b2, 20191226
[INFO   ] [Kivy        ] Installed at "/Users/richard/Library/Developer/CoreSimulator/Devices/E5F90713-0057-4F0B-A728-F6F27038B40F/data/Containers/Bundle/Application/63E7CD24-75E2-41E9-8851-8E556D5419D1/gps.app/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.1 (default, Dec 26 2019, 21:38:06) 
[Clang 11.0.0 (clang-1100.0.33.12)]
[INFO   ] [Python      ] Interpreter at "/Users/richard/Library/Developer/CoreSimulator/Devices/E5F90713-0057-4F0B-A728-F6F27038B40F/data/Containers/Bundle/Application/63E7CD24-75E2-41E9-8851-8E556D5419D1/gps.app/gps"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_imageio, img_tex, img_gif (img_dds, img_sdl2, img_ffpyplayer, img_pil ignored)
Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 1): no suitable image found.  Did find:
	/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation: mach-o, but not built for iOS simulator
Got fallback dlopen error on Foundation: dlopen(/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 1): image not found
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0 APPLE-17.10.22'>
[INFO   ] [GL          ] OpenGL vendor <b'Apple Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Apple Software Renderer'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <4096>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
2019-12-26 22:15:16.918692+0200 gps[66253:28061256] Unbalanced calls to begin/end appearance transitions for <SDL_uikitviewcontroller: 0x7f9d9f72fc00>.
2019-12-26 22:15:16.918836+0200 gps[66253:28061256] Unbalanced calls to begin/end appearance transitions for <SDL_uikitviewcontroller: 0x7f9d9f72fc00>.
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/Users/richard/Repos/kivy-ios/gps-ios/YourApp/main.py", line 71, in <module>
   File "/Users/richard/Library/Developer/CoreSimulator/Devices/E5F90713-0057-4F0B-A728-F6F27038B40F/data/Containers/Bundle/Application/63E7CD24-75E2-41E9-8851-8E556D5419D1/gps.app/lib/python3.7/site-packages/kivy/app.py", line 950, in run
     runTouchApp()
   File "/Users/richard/Library/Developer/CoreSimulator/Devices/E5F90713-0057-4F0B-A728-F6F27038B40F/data/Containers/Bundle/Application/63E7CD24-75E2-41E9-8851-8E556D5419D1/gps.app/lib/python3.7/site-packages/kivy/base.py", line 560, in runTouchApp
     EventLoop.mainloop()
   File "/Users/richard/Library/Developer/CoreSimulator/Devices/E5F90713-0057-4F0B-A728-F6F27038B40F/data/Containers/Bundle/Application/63E7CD24-75E2-41E9-8851-8E556D5419D1/gps.app/lib/python3.7/site-packages/kivy/base.py", line 334, in mainloop
     self.idle()
   File "/Users/richard/Library/Developer/CoreSimulator/Devices/E5F90713-0057-4F0B-A728-F6F27038B40F/data/Containers/Bundle/Application/63E7CD24-75E2-41E9-8851-8E556D5419D1/gps.app/lib/python3.7/site-packages/kivy/base.py", line 375, in idle
     Clock.tick()
   File "/Users/richard/Library/Developer/CoreSimulator/Devices/E5F90713-0057-4F0B-A728-F6F27038B40F/data/Containers/Bundle/Application/63E7CD24-75E2-41E9-8851-8E556D5419D1/gps.app/lib/python3.7/site-packages/kivy/clock.py", line 646, in tick
     self.post_idle(ts, self.idle())
   File "/Users/richard/Library/Developer/CoreSimulator/Devices/E5F90713-0057-4F0B-A728-F6F27038B40F/data/Containers/Bundle/Application/63E7CD24-75E2-41E9-8851-8E556D5419D1/gps.app/lib/python3.7/site-packages/kivy/clock.py", line 689, in post_idle
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "/Users/richard/Library/Developer/CoreSimulator/Devices/E5F90713-0057-4F0B-A728-F6F27038B40F/data/Containers/Bundle/Application/63E7CD24-75E2-41E9-8851-8E556D5419D1/gps.app/lib/python3.7/site-packages/kivy/clock.py", line 1002, in callback_func
     func(*args, **kwargs)
 TypeError: on_status() missing 1 required positional argument: 'status'
2019-12-26 22:15:23.734401+0200 gps[66253:28061256] Application quit abnormally!
2019-12-26 22:15:23.775014+0200 gps[66253:28061256] Leaving
```
This is using the latest example in `plyer/example/gps`. Has the signature of a function changed somewhere? I notice my build uses the latest kivy 2.0.0.dev0. Could this be the issue?

**Comment by Zen-CODE** [comment]
I can fix it by changing the example as follows:
```
    @mainthread
    def on_status(self, stype, status, *args):
        self.gps_status = 'type={}\n{}'.format(stype, status)
        Logger.info("Extra args: {0}".format(args))
```
But then I get the following:
```
[INFO   ] [GL          ] NPOT texture support is available
2019-12-26 22:30:30.929906+0200 gps[66641:28111476] Unbalanced calls to begin/end appearance transitions for <SDL_uikitviewcontroller: 0x7fb1d0430490>.
2019-12-26 22:30:30.930080+0200 gps[66641:28111476] Unbalanced calls to begin/end appearance transitions for <SDL_uikitviewcontroller: 0x7fb1d0430490>.
```

**Comment by Dirk-Sandberg** [comment]
Oh, in the example app, it expects there to be the two arguments, `stype` and `status`, which is what's passed on Android (see line 52 in https://github.com/kivy/plyer/blob/master/plyer/platforms/android/gps.py)

What I put in for iOS basically doesn't pass anything for the `stype` attribute, just the `status` string. In the plyer gps example it expects both arguments, but my change only passes the one, which it interprets as the `stype` and throws your error about the missing `status` argument. Maybe the thing to do would be add something for the `stype` argument in iOS as well?

You should be able to test the functionality by going to your iPhone's Settings -> Your App -> Location Services -> toggle this back and forth, your app will respond when you go back to it from settings.

**Comment by Zen-CODE** [comment]
Yes, I  think adding that is important, and the point of plyer is to have a standard interface for all OS's. I there a meaningful value one could pass in? What would *sytpe* value be in Android? And is there not a logical equivalent for iOS?

I'm actually testing on the iOS simulator - don't have an iOS device. But when I turn off location access (similarly to above), I get.
```
 TypeError: on_status() missing 1 required positional argument: 'status'
2019-12-26 22:49:54.319145+0200 gps[66846:28141691] Application quit abnormally!
2019-12-26 22:49:54.388629+0200 gps[66846:28141691] Leaving
```
So if we can add that parameter, it's looking good otherwise? :-)

**Comment by Zen-CODE** [comment]
In view of what the Android provider generates here, for consistency, I think the status should be one of:
* 'provider-disabled'
* 'provider-enabled'
* 'provider-status'

The second parameter seems like a status code, and not important, so I'd be happy with pretty much any value passed in (None possible, or a matching int if you want to scour the android status codes)....

https://github.com/kivy/plyer/blob/1158444c1707631bd1b9b94ed1975bf83885b226/plyer/platforms/android/gps.py#L33

**Comment by Dirk-Sandberg** [comment]
Here are the `status` strings that come out of iOS: https://developer.apple.com/documentation/corelocation/clauthorizationstatus

iOS is a little different from Android because iOS seems like it would always pass the `provider-status`, and then it would be `provider-status: %s`%status_code. There aren't separate functions for Provider Enabled, Provider Disabled, and Provider Status Changed like on Android -- it's all in the one function on iOS.

Or maybe we do something on iOS like set provider_mode to `provider-disabled` if `status == 'denied'. I don't know what the case would be for `provider-enabled` since that seems to logically overlap with `provider-status` for iOS.

Did I explain that decently? Just woke up ;)

**Comment by Zen-CODE** [comment]
Yeah, makes total sense. And seeing as we are never going to get them entirely consistent, I agree with you name choices, but passing the as matching android values in as the "provider" value i.e.
```
        if status == 0:
            status_msg = "notDetermined"
            provider = 'provider-disabled'
        elif status == 1:
            status_msg = "restricted"
            provider = 'provider-enabled'
        elif status == 2:
            status_msg = "denied"
            provider = 'provider-disabled'
        elif status == 3:
            status_msg = "authorizedAlways"
            provider = 'provider-enabed'
        elif status == 4:
            status_msg = "authorizedWhenInUse"
            provider = 'provider-enabled'
        if self.on_status:
            self.on_status(provider, status_msg
```
But yeah, it's messy and certainly not clean enough for me to get to insistent upon. I suggested make a call, but as long as it works (it needs a second parameter), getting it working is a great step forward. Thanks :-)

**Comment by Dirk-Sandberg** [comment]
We're on the same page! I tried to mimic the Android facade as much as possible. Now the first argument of `on_status` will be 'provider-enabled' or 'provider-disabled' (although that's missing the last Android case of 'provider-status'). The second argument will have the same form of 'provider: status_message', but the provider string will just always be set to 'standard-ios-provider'. The status_message string will be a more detailed description of the GPS status.

Cross platform usage will might look something like:
```

def on_status(self, stype, status):
    if stype == 'provider-enabled' or stype == 'provider-status':
        # GPS is available
    elif stype == 'provider-disabled':
        # GPS is not enabled

```

**Comment by Zen-CODE** [comment]
Perfect! Nicely done! And works like charm.  Many thanks

**Pull request merged**
