### PR TITLE
Audio recording iOS, OSX

### PR DESCRIPTION
**Pull request by kiok46**
Add audio recording.
record, stop, pause the recording.

### CODE REVIEW

**Comment by pedrosimao** [comment]
So, why this pull request was still not accepted? Is audio recording already possible in iOS?

**Comment by kiok46** [comment]
@pedrosimao because it's still under development and not properly tested yet.

**Comment by pedrosimao** [comment]
@kiok46 ok, thanks a lot for your answer. The pull request was done it's been more than a half year. So it was wondering if it was abandoned.

**Comment by kiok46** [comment]
@pedrosimao  No, It's not abandoned. I can't find time to work on this one. But I can see that it's not good for use and some methods are not implemented well.
closing it, maybe someone can get an inspiration from this code and open a new PR.

**Pull request closed without merging**
