### PR TITLE
Add on_pause function

### PR DESCRIPTION
**Pull request by malverick**
Some of the example apps does not contain `on_pause` function due to which, when the app is relaunched after pressing the home button, app restarts. Adding the `on_pause` function will cause the app to start from state where it was before leaving.

### CODE REVIEW

**Comment by kiok46** [comment]
@malverick  Thanks.

**Comment by dessant** [comment]
@kiok46, @malverick, this is becoming `unnecessary` since on_pause returns True in kivy master.

**Comment by kiok46** [comment]
kivy/kivy#4603 Now I remember, thanks.

**Comment by malverick** [comment]
Hi @rockcastle . Can you please share the android logs?

**Comment by rockcastle** [comment]
Hi, 
Sorry, I already clear logs, I can send debugged apk if it is ok.

**Comment by malverick** [comment]
That would be fine.

**Comment by rockcastle** [comment]
I have tried one more time creating apk and done also it works fine on tablet which is android 5.1.          I have uploaded my buildozer.spec and main.py to my GitHub ( https://github.com/rockcastle/Python-Kivy-Android-app )
I have realized that autoclass('org.rendy.android.PythonActivity') not used any on crystax-ndk python3, instead of use autoclave('org.kivy.android.PythonActivity')

By the way thanks.

**Comment by dessant** [comment]
@rockcastle, please move the discussion to irc or the mailing list.

**Pull request merged**
