### PR TITLE
Android light sensor

### PR DESCRIPTION
**Pull request by malverick**
Android light sensor api to measure the ambient light level(illumination) in lx.

Can be merged.

screenshot_2017-02-24-00-49-28-434_org test plyerlight
screenshot_2017-02-24-00-49-45-054_org test plyerlight

Tested on:
Device - Xiaomi Mi 4i
Toolchain - old and new both
Android sdk - 24
Android api - 19

### CODE REVIEW

**Comment by dessant** [comment]
Hopefully ios will have an api for it in the future, i see UWP already has:
https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/use-the-light-sensor

**Comment by malverick** [comment]
Thanks @dessant .

**Comment by dessant** [comment]
@malverick, the README table was messed up. 😛

**Comment by malverick** [comment]
Sorry @dessant. It was messed up in my editor too so I edited it but after pushing the changes it again got messed up which I forgot to notice. Sorry. I will create a new pr after fixing it.

**Comment by malverick** [comment]
I think this is happening when I directly commiting from github. Right now also when I am directly trying to edit the README file, there is nothing to fix. It's absolutely fine.
I will fix it in my system and then push the changes within an hour. I don't have access to my laptop right now.

**Pull request merged**
