### PR TITLE
Introduce camera access for ios and a example.

### PR DESCRIPTION
**Pull request by akshayaurora**
Depends upon Photolibrary on iOS https://github.com/kivy/kivy-ios/pull/154

### CODE REVIEW

**Comment by gorgonaut04** [comment]
What is the holdup for this merge? It would appear to add a significant capability to kivy-ios

**Comment by dessant** [comment]
@gorgonaut04, it was not tested yet. Would you mind checking out the camera_gallery_ios branch and reporting back?

**Comment by gorgonaut04** [comment]
I intend to, but I need to drive 2 hours to use an imac, and won't be able to for about 2 weeks. The availability of this feature is really the catalyst for getting started on an iOS version of our android app ( barlyapp.com ). We really aren't iOS people at all, so we're hoping that Kivy would make the jump easier

**Comment by gorgonaut04** [comment]
I intend to, but I need to drive 2 hours to use an imac, and won't be able to for about 2 weeks. The availability of this feature is really the catalyst for getting started on an iOS version of our android app ( barlyapp.com ). We really aren't iOS people at all, so we're hoping that Kivy would make the jump easier

**Comment by gorgonaut04** [comment]
I intend to, but I need to drive 2 hours to use an imac, and won't be able to for about 2 weeks. The availability of this feature is really the catalyst for getting started on an iOS version of our android app ( barlyapp.com ). We really aren't iOS people at all, so we're hoping that Kivy would make the jump easier

**Comment by dessant** [comment]
If others do not jump in for testing, we would be glad to get feedback on it two weeks from now. ;)

**Comment by mixedCase** [comment]
Any news on this?

**Comment by gorgonaut04** [comment]
I finally got a chance to focus on getting iOS going and I can confirm that the camera works great!! This was actually one of the easier features to port over. Thanks @akshayaurora!

**Pull request merged**
