### PR TITLE
Android Gravity Sensor

### PR DESCRIPTION
**Pull request by malverick**
@dessant I have tested the api and done the required changes(much changes were not required though).
I request you to review the pr. From my side, it can be merged.
screenshot_2017-02-09-18-18-15-137_org test plyergravity
screenshot_2017-02-09-18-18-25-355_org test plyergravity

### CODE REVIEW

**Comment by malverick** [comment]
reference #161

**Comment by dessant** [comment]
Thanks for your work, though I believe the original commits should be preserved. Please merge the pr branch into your own working branch, and add your changes on top of that.

**Comment by dessant** [comment]
@malverick, please also list the devices, toolchain and api versions you tested the new pr with.

**Comment by dessant** [comment]
One more thing, make sure to write proper commit messages, as prs which build on other people's work will not be squashed upon merging.

**Comment by malverick** [comment]
ok @dessant I will do as you say.

**Pull request closed without merging**
