### PR TITLE
Camera example

### PR DESCRIPTION
**Pull request by trivedigaurav**
This is the basic example for the camera facade. Saves the image with the name given by the user.

### CODE REVIEW

**Comment by redfast00** [comment]
@trivedigaurav I have the same problem as @amalgamatedclyde (pressing checkmark does nothing), but when I return to the application (by pressing X), I get a 'could not save picture' popup. Cyanogenmod 13.0 (Android 6) on OnePlus Two.

**Comment by kiok46** [comment]
@redfast00  I will look into this in a couple of days (Have exams now).

**Comment by redfast00** [comment]
@kiok46: Would you mind if I opened an issue?

**Comment by dessant** [comment]
@redfast00, if you're convinced the bug is not in this pull request, but in plyer, then an issue whould be ok. Otherwise sorting it out on this thread is recommended.

**Comment by kiok46** [comment]
@redfast00  Also, there is already an issue opened by @brousch  demanding a working example for camera façade. #16

**Comment by akshayaurora** [comment]
@thegrymek thanks

**Pull request merged**
