### PR TITLE
Add file chooser facade and support for Linux and Windows

### PR DESCRIPTION
**Pull request by Davideddu**
I renamed the branch to avoid confusion with qua-non's branch (native_dialogs) and reopened this pull request. It should be up to date with master now.

Needs testing for Windows.

The Mac OS X implementation will be ported soon.

### CODE REVIEW

**Comment by Davideddu** [comment]
I added support for Mac OS X,. but it needs testing.
Particularly,  I need you to test:

* multiple=True - multiple file selection, please report any exceptions
* filters=[list of wildcards] - provide a list of wildcards like this: ["*.mp3", "*jpg", "JPG", "*pn*"]
* filters=[list of extensions], use_extensions=True - provide a list of extensions like this: ["mp3", "jpg", "png"]

**Comment by tito** [comment]
That's awesome!

**Comment by akshayaurora** [comment]
@Davideddu could you rebase? there is a conflict while merging right now.

**Comment by Davideddu** [comment]
@akshayaurora Done.

**Comment by Davideddu** [comment]
Please make sure you edit the README to add the line for the IR blaster. Also I had to add "irblaster" to __all__ in plyer/__init__.py

**Pull request merged**
