### PR TITLE
Gyroscope uncalibrated sensor

### PR DESCRIPTION
**Pull request by malverick**
Methods for accessing gyroscope uncalibrated sensor are added in current gyroscope API.
Example for gyroscope api is also created.

Tested and working fine. Can be merged.

### CODE REVIEW

**Comment by malverick** [comment]
Added the iOS implementation to retrieve uncalibrated values.

**Comment by malverick** [comment]
I have removed the mentioning the unit of readings received from the sensor because in `Android` the readings are in `rad/s` but in iOS there is no mentioning of the unit of readings so it is best to not mention it at all.

**Comment by akshayaurora** [comment]
@malverick thanks 👍

**Comment by malverick** [comment]
@akshayaurora your welcome :)

**Pull request merged**
