### PR TITLE
implementing fingerprint authentication

### PR DESCRIPTION
**Pull request by phunsukwangdu**
I am very excited to work on this feature and currently getting my grip on it.
issue #247   
There might be some errors lurking in it thus i request some guidance and support. 
Note:- The pr is not in mergeable state .Further works required.

### CODE REVIEW

**Comment by akshayaurora** [comment]
Please don't park! open a request when it is ready to be merged or least has some actual work in it.

**Comment by phunsukwangdu** [comment]
@akshayaurora i was working on it. :) Nevertheless i will open a new pr.

**Comment by tshirtman** [comment]
you can still push to that branch, and reopen the pull later (if you can't, just ask so we do).

**Comment by mcroni** [comment]
Did this project get abandoned

**Pull request closed without merging**
