### PR TITLE
Facade Wifi

### PR DESCRIPTION
**Pull request by bhaveshAn**

### CODE REVIEW

**Comment by bhaveshAn** [comment]
Is in a mergeable state.
Kindly review it.

**Comment by KeyWeeUsr** [comment]
I wonder how did this happened. there's literally no `_get_access_points` in the whole repo and it stayed like that for 9 months.

**Comment by bhaveshAn** [comment]
Yes, and for this reason the wifi facade faced problems running in the platforms it was implemented.

**Comment by KeyWeeUsr** [comment]
https://github.com/kivy/plyer/pull/301/files#diff-dfab4e5b79aa27cad70ea28e6401beadL90

**Pull request merged**
