### PR TITLE
Storage path API

### PR DESCRIPTION
**Pull request by malverick**
Tested and working fine. Can be merged.

Tested on -
Device - Xiaomi Redmi Note 4
Android api - 19
Android sdk - 20
Android ndk - 9c
whatsapp image 2017-06-15 at 12 56 28 am

### CODE REVIEW

**Comment by amadeusxnet** [comment]
> 06-15 22:00:10.467  4975  4993 I python  :  Traceback (most recent call last):
> 06-15 22:00:10.468  4975  4993 I python  :    File "/home/nemo/Desktop/plyer-storage_path/examples/storagepath/.buildozer/android/app/main.py", line 8, in <module>
> 06-15 22:00:10.468  4975  4993 I python  :  ImportError: cannot import name storagepath
> 06-15 22:00:10.488  4975  4993 I python  : Python for android ended.
>

**Comment by amadeusxnet** [comment]
Solved it easily!

**Comment by akshayaurora** [comment]
@malverick thanks 👍

**Comment by malverick** [comment]
thanks @akshayaurora

**Comment by saccode** [comment]
Can't import storagepath 
I tried to upgrade to plyer no luck, also tried uninstall and reinstall but no luck.. 
Is this "storagepath" feature/module is ready to use?

>>> from plyer import tts
>>>
>>>
>>> from plyer import storagepath
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name storagepath
>>>

**Comment by malverick** [comment]
Hi @saccode . The API is working for me. Make sure you are installing the plyer through this repository and not from pip.

**Pull request merged**
