### PR TITLE
fix #107 - Use Android_ID instead of IMEI

### LINKED ISSUE #107: AndroidUniqueID doesn't use Android ID
The implementation returns the IMEI and therefore only works on phones, not tablets. Android provides an Android ID via Secure Settings which works for all devices and does not require any extra permissions (the current implementation requires READ_PHONE_STATE).

Example:
````python
PythonActivity = autoclass('org.renpy.android.PythonActivity')
Secure = autoclass('android.provider.Settings$Secure')
android_id = Secure.getString(PythonActivity.mActivity.getContentResolver(),
                              Secure.ANDROID_ID)
````

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7940424-androiduniqueid-doesn-t-use-android-id?utm_campaign=plugin&utm_content=tracker%2F77151&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F77151&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by aron-bordin**
Using Android_ID. 
Do I need to add something else?

### CODE REVIEW

**Comment by Kovak** [comment]
An important observation:

[14:20] <tito> use "from plyer.platforms.android import activity" instead of manually importing PythonActivity
[14:21] <tito> otherwise the code will be broken when used in service
[14:21] <tito> dessant: ie, use: https://github.com/kivy/plyer/blob/master/plyer/platforms/android/__init__.py

**Comment by aron-bordin** [comment]
PR updated. Please, when possible, let me know if it's ok now.

**Comment by dessant** [comment]
Looks great, but we missed to merge this before refactoring the facades. Could you please update it and add a versionchanged tag with a short mention of the change on android? It should be merged right after that.

**Comment by aron-bordin** [comment]
PR updated, check if it's ok

**Comment by dessant** [comment]
Thanks a lot. :+1:

**Pull request merged**
