### PR TITLE
Update Wifi Module

### PR DESCRIPTION
**Pull request by manthansharma**
Add more functionality for wifi module and remove old bugs

### CODE REVIEW

**Comment by kiok46** [comment]
Hi! @manthansharma  thanks for contributing, could you please resolve the conflicts and also add implementation for windows?

**Comment by manthansharma** [comment]
Can some please review and merge this PR.

**Comment by kiok46** [comment]
@manthansharma  We can only merge this if we also have implementation for other platforms as well or if that is not possible then handle them for each platform.
Thanks.

**Comment by KeyWeeUsr** [comment]
Closing in favor of #473, commits preserved.

**Pull request closed without merging**
