### PR TITLE
Call for ios

### PR DESCRIPTION
**Pull request by kiok46**
Some days ago a user on IRC was asking about calling feature for ios, Here it is.
I have not tested it yet, maybe I will do it in a couple of days.

### CODE REVIEW

**Comment by doratoa** [comment]
Maybe it was me! Thanks, I'll check it as soon as I get testing device.

**Comment by doratoa** [comment]
Nope, it breaks with 
`'NSURL' object is not callable`
on iPhone 6 and simulators (not sure if simulators do have any mock call implementation, but error is the same as on a real device). Or I'm doing something wrong since I didn't find any call documentation: if it needs some permissions like GPS or if there is a required format for number input.
Further input would be appreciated!

**Comment by doratoa** [comment]
Ok, sorry for delay, we were busy making our app ready for AppStore.
But thanks to you, it will be rolling out with call feature! ^\_~+
We use **call** button to let our user call service operator right from the app.
That how feature **first worked** with last fixes on test: _(it's purely local service so it's untranslated except my notes)_
```
# App
def calltest(self):
   try:
      plyer.call.makecall(tel='8965????28') #  NOTE edited for privacy
   except Exception as exc:
      pass
```
```
# kv
BoxLayout:
   orientation: "vertical"
   size_hint: 1, 0.6
   spacing: "4sp"
   FixWidthButton:
       text: "КАРТА"
       on_release: app.activate_screen('scr_map')
   FixWidthButton:
       text: "ОБРАТНАЯ СВЯЗЬ"
       on_release: app.activate_screen('scr_feed')
   FixWidthButton:
       text: "Звонок ТЕСТ"
       on_release: app.calltest() #  <- this one
   FixWidthButton:
       text: "РЕГИСТРАЦИЯ"
       on_release: app.activate_screen('scr_reg')
   FixWidthButton:
      text: app.btn_account_loginout_text
      on_release: app.btn_account_loginout_action()
```
_both screenshots are taken from same iphone 6s, regrettably I was unable to find a way to show status bar in app yet, so you can't see it on first one_
ioscall_ip6s1
_I was told that call is aborted when taking screencapture on iphone, so it's finished on this one (but I got the call alright, ofc)_
ioscall_ip6s0

**Comment by kiok46** [comment]
@doratoa Thanks for testing and the screenshots.  :+1:

**Pull request merged**
